apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supermario-app-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-1:600920219683:certificate/616f8af1-e304-424d-a2f5-1eb8dc248310"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  ingressClassName: alb
  rules:
    - host: "supermario.sbaylab.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supermario-service
                port:
                  number: 80